# Minimal prompt: directory, git, python, then newline + lambda prompt

format = """
$directory$git_branch$git_status$python
λ """

add_newline = false


[directory]
# Remove color style to use terminal default
style = "none"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"


[git_branch]
symbol = " "
style = "bold green"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold red"
format = "[$all_status]($style)"

[python]
symbol = ""
style = "bold yellow"
format = "[$symbol$virtualenv]($style)"

# Disable everything else
[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[time]
disabled = true

[character]
disabled = true

